development:
  adapter: postgresql
  database: kottans-ruby-development
  host: localhost
  username: dima
  password: dima

test:
  adapter: postgresql
  database: kottans-ruby-test
  host: localhost
  username: dima
  password: dima
